# Generated by Django 3.2.18 on 2024-02-14 10:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('poste', models.CharField(max_length=200)),
                ('evalue_nom', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('evalue_nom', models.CharField(max_length=200)),
                ('evalue_prenom', models.CharField(max_length=200)),
                ('evale_mail', models.EmailField(max_length=200)),
                ('evalue_poste', models.CharField(max_length=200)),
                ('time', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)], default=2024, verbose_name='time')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('owner_evalue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evalue_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Thematique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluationapp.evaluation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contributeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contributeur', models.CharField(choices=[('Beneficiaire', 'Beneficiaire'), ('Collegue', 'Collegue en lien fonctionnel'), ('Agent_encadre', 'Agent encadre')], default='Beneficiaire', max_length=20)),
                ('contributeur1_nom', models.CharField(max_length=200)),
                ('contributeur1_prenom', models.CharField(max_length=200)),
                ('contributeur1_mail', models.EmailField(max_length=200)),
                ('contributeur2_nom', models.CharField(max_length=200)),
                ('contributeur2_prenom', models.CharField(max_length=200)),
                ('contributeur2_mail', models.EmailField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributeur', to='evaluationapp.evaluation')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Avis_Encadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_contributeur', models.CharField(max_length=200)),
                ('nom_evalue', models.CharField(max_length=200)),
                ('note_1', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_note_1', models.CharField(max_length=400)),
                ('note_2', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_note_2', models.CharField(max_length=400)),
                ('note_3', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_note_3', models.CharField(max_length=400)),
                ('note_4', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_note_4', models.CharField(max_length=400)),
                ('note_5', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_note_5', models.CharField(max_length=400)),
                ('note_6', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_note_6', models.CharField(max_length=400)),
                ('commentaire', models.CharField(max_length=900)),
                ('evaluation_titre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_encadre', to='evaluationapp.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Avis_B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_contributeur', models.CharField(max_length=200)),
                ('nom_evalue', models.CharField(max_length=200)),
                ('note_1', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_note_1', models.CharField(max_length=400)),
                ('note_2', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_note_2', models.CharField(max_length=400)),
                ('note_3', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_note_3', models.CharField(max_length=400)),
                ('note_4', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_note_4', models.CharField(max_length=400)),
                ('note_5', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_note_5', models.CharField(max_length=400)),
                ('note_6', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_note_6', models.CharField(max_length=400)),
                ('commentaire', models.CharField(max_length=900)),
                ('evaluation_titre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_beneficiaire', to='evaluationapp.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Avis_Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_contributeur', models.CharField(max_length=200)),
                ('nom_evalue', models.CharField(max_length=200)),
                ('note_1', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_note_1', models.CharField(max_length=400)),
                ('note_2', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_note_2', models.CharField(max_length=400)),
                ('note_3', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_note_3', models.CharField(max_length=400)),
                ('note_4', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_note_4', models.CharField(max_length=400)),
                ('note_5', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_note_5', models.CharField(max_length=400)),
                ('note_6', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_note_6', models.CharField(max_length=400)),
                ('commentaire', models.CharField(max_length=900)),
                ('evaluation_titre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_agent', to='evaluationapp.evaluation')),
            ],
        ),
    ]
