# Generated by Django 3.2.18 on 2024-02-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluationapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis_encadre',
            name='commentaire',
        ),
    ]
